#
# Amazon EC2 example cluster configuration
#
ectwo:
    - flink-version "0.10.1"					# Version of Flink
    - hadoop-version "2.6.0"					# Version of Hadoop
    - scala-version "2.10"                    # Version of Scala
    - image "us-west-2/ami-5189a661"				# Ubuntu 14.04 LTS AMI
    - region "us-west-2"					# Region
    - m3.medium {MASTER,UI}           			# Request service
    - m3.medium {WORKER}					# Request service
   # - m3.medium {WORKER}					# Request service
   # - m1.medium {WORKER}					# Request service
    - remote-exec-preconfig {cd ~, echo hey > hey.txt}
    - remote-exec-postconfig {}
